import { createHmac, timingSafeEqual } from "node:crypto";
import { mkdir, open, readFile, stat, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import type { StorageAdapter } from "./types";

/**
 * Development-only storage on local disk (./.data/uploads). Mimics the S3 flow:
 * the browser PUTs to a signed URL on /api/media/upload, files are served from
 * /api/media/file/<key>. Not for production: Vercel's filesystem is ephemeral.
 */

const ROOT = path.join(process.cwd(), ".data", "uploads");
const TTL_MS = 5 * 60 * 1000;

export function localPath(key: string): string {
  const resolved = path.resolve(ROOT, key);
  // Keys are generated by us, but never allow escaping the uploads folder.
  if (!resolved.startsWith(ROOT + path.sep)) throw new Error("invalid storage key");
  return resolved;
}

export function signLocalUpload(secret: string, key: string, contentType: string, length: number, exp: number): string {
  return createHmac("sha256", secret).update(`${key}\n${contentType}\n${length}\n${exp}`).digest("hex");
}

export function verifyLocalUpload(
  secret: string,
  q: { key: string; contentType: string; length: number; exp: number; sig: string },
): boolean {
  if (!Number.isFinite(q.exp) || q.exp < Date.now()) return false;
  const expected = Buffer.from(signLocalUpload(secret, q.key, q.contentType, q.length, q.exp), "hex");
  const given = Buffer.from(q.sig, "hex");
  return given.length === expected.length && timingSafeEqual(given, expected);
}

export async function writeLocalObject(key: string, data: Uint8Array, contentType: string): Promise<void> {
  const file = localPath(key);
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, data);
  await writeFile(`${file}.meta.json`, JSON.stringify({ contentType }));
}

export async function readLocalObject(key: string): Promise<{ data: Buffer; contentType: string } | null> {
  try {
    const file = localPath(key);
    const [data, meta] = await Promise.all([readFile(file), readFile(`${file}.meta.json`, "utf8")]);
    return { data, contentType: (JSON.parse(meta) as { contentType: string }).contentType };
  } catch {
    return null;
  }
}

export function createLocalStorage(opts: { secret: string; baseUrl: string }): StorageAdapter {
  return {
    driver: "local",

    async createUploadUrl({ key, contentType, contentLength }) {
      const exp = Date.now() + TTL_MS;
      const sig = signLocalUpload(opts.secret, key, contentType, contentLength, exp);
      const url = new URL(`${opts.baseUrl}/api/media/upload`);
      url.search = new URLSearchParams({ key, type: contentType, len: String(contentLength), exp: String(exp), sig }).toString();
      return { url: url.toString(), headers: { "content-type": contentType } };
    },

    async head(key) {
      try {
        const file = localPath(key);
        const [s, meta] = await Promise.all([stat(file), readFile(`${file}.meta.json`, "utf8")]);
        return { size: s.size, contentType: (JSON.parse(meta) as { contentType: string }).contentType };
      } catch {
        return null;
      }
    },

    async readStart(key, bytes) {
      try {
        const fh = await open(localPath(key), "r");
        try {
          const buf = Buffer.alloc(bytes);
          const { bytesRead } = await fh.read(buf, 0, bytes, 0);
          return new Uint8Array(buf.subarray(0, bytesRead));
        } finally {
          await fh.close();
        }
      } catch {
        return null;
      }
    },

    async delete(key) {
      const file = localPath(key);
      await Promise.allSettled([unlink(file), unlink(`${file}.meta.json`)]);
    },

    publicUrl(key) {
      return `${opts.baseUrl}/api/media/file/${key}`;
    },
  };
}
