import { sql } from "drizzle-orm";
import { customType, pgPolicy, pgRole, timestamp, uuid } from "drizzle-orm/pg-core";

/** Case-insensitive text (Postgres `citext` extension, created in the bootstrap migration). */
export const citext = customType<{ data: string }>({
  dataType() {
    return "citext";
  },
});

/** Primary key: time-ordered UUID v7 generated by the database (see bootstrap migration). */
export const id = () =>
  uuid("id")
    .primaryKey()
    .default(sql`uuid_generate_v7()`);

export const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
export const updatedAt = () =>
  timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

/**
 * The database role every tenant-scoped query runs as (`SET LOCAL ROLE app_tenant`
 * inside withTenant). Created by the bootstrap migration, so drizzle-kit treats it
 * as existing.
 */
export const appTenant = pgRole("app_tenant").existing();

/**
 * Standard tenant-isolation policy: rows are visible/writable only when their
 * store_id equals the transaction's `app.store_id` setting. When the setting is
 * missing, current_store_id() is NULL and nothing matches (fails closed).
 */
export const tenantPolicy = (column: "store_id" | "id" = "store_id") =>
  pgPolicy("tenant_isolation", {
    as: "permissive",
    for: "all",
    to: appTenant,
    using: sql.raw(`${column} = current_store_id()`),
    withCheck: sql.raw(`${column} = current_store_id()`),
  });
